// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import DeleteFileReducer from "../delete_file_reducer";
import UploadFileReducer from "../upload_file_reducer";

export type DeleteFileParams = __Infer<typeof DeleteFileReducer>;
export type UploadFileParams = __Infer<typeof UploadFileReducer>;

