// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CancelUploadReducer from "../cancel_upload_reducer";
import DeleteTransferReducer from "../delete_transfer_reducer";
import FinishUploadReducer from "../finish_upload_reducer";
import SealTransferReducer from "../seal_transfer_reducer";
import StartUploadV2Reducer from "../start_upload_v_2_reducer";
import UpdateTransferExpiryReducer from "../update_transfer_expiry_reducer";
import UploadChunkReducer from "../upload_chunk_reducer";
import UploadFileReducer from "../upload_file_reducer";

export type CancelUploadParams = __Infer<typeof CancelUploadReducer>;
export type DeleteTransferParams = __Infer<typeof DeleteTransferReducer>;
export type FinishUploadParams = __Infer<typeof FinishUploadReducer>;
export type SealTransferParams = __Infer<typeof SealTransferReducer>;
export type StartUploadV2Params = __Infer<typeof StartUploadV2Reducer>;
export type UpdateTransferExpiryParams = __Infer<typeof UpdateTransferExpiryReducer>;
export type UploadChunkParams = __Infer<typeof UploadChunkReducer>;
export type UploadFileParams = __Infer<typeof UploadFileReducer>;

