// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CancelUploadReducer from "../cancel_upload_reducer";
import DeleteFileReducer from "../delete_file_reducer";
import FinishUploadReducer from "../finish_upload_reducer";
import StartUploadReducer from "../start_upload_reducer";
import StartUploadV2Reducer from "../start_upload_v_2_reducer";
import UploadChunkReducer from "../upload_chunk_reducer";
import UploadFileReducer from "../upload_file_reducer";

export type CancelUploadParams = __Infer<typeof CancelUploadReducer>;
export type DeleteFileParams = __Infer<typeof DeleteFileReducer>;
export type FinishUploadParams = __Infer<typeof FinishUploadReducer>;
export type StartUploadParams = __Infer<typeof StartUploadReducer>;
export type StartUploadV2Params = __Infer<typeof StartUploadV2Reducer>;
export type UploadChunkParams = __Infer<typeof UploadChunkReducer>;
export type UploadFileParams = __Infer<typeof UploadFileReducer>;

