// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u8().primaryKey(),
  totalFiles: __t.u64().name("total_files"),
  totalFileBytes: __t.u64().name("total_file_bytes"),
  totalTrafficBytes: __t.u64().name("total_traffic_bytes"),
  onlineConnections: __t.u64().name("online_connections"),
  updatedAt: __t.timestamp().name("updated_at"),
});
