// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const FileBlob = __t.object("FileBlob", {
  id: __t.u64(),
  content: __t.byteArray(),
});
export type FileBlob = __Infer<typeof FileBlob>;

export const StoredFile = __t.object("StoredFile", {
  id: __t.u64(),
  name: __t.string(),
  mimeType: __t.string(),
  sizeBytes: __t.u64(),
  createdAt: __t.timestamp(),
});
export type StoredFile = __Infer<typeof StoredFile>;

