// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const CreatedTransferResult = __t.object("CreatedTransferResult", {
  transferId: __t.u64(),
  pickupCode: __t.string(),
  expiresAtMicros: __t.u64(),
});
export type CreatedTransferResult = __Infer<typeof CreatedTransferResult>;

export const FileBlob = __t.object("FileBlob", {
  id: __t.u64(),
  content: __t.byteArray(),
});
export type FileBlob = __Infer<typeof FileBlob>;

export const FileChunk = __t.object("FileChunk", {
  id: __t.u64(),
  fileId: __t.u64(),
  chunkIndex: __t.u32(),
  content: __t.byteArray(),
});
export type FileChunk = __Infer<typeof FileChunk>;

export const OwnedTransferResult = __t.object("OwnedTransferResult", {
  transferId: __t.u64(),
  pickupCode: __t.string(),
  createdAt: __t.timestamp(),
  expiresAtMicros: __t.u64(),
  sealed: __t.bool(),
  fileCount: __t.u32(),
  totalSizeBytes: __t.u64(),
});
export type OwnedTransferResult = __Infer<typeof OwnedTransferResult>;

export const StoredFile = __t.object("StoredFile", {
  id: __t.u64(),
  transferId: __t.u64(),
  name: __t.string(),
  mimeType: __t.string(),
  sizeBytes: __t.u64(),
  createdAt: __t.timestamp(),
  ready: __t.bool(),
  chunkCount: __t.u32(),
  chunkSizeBytes: __t.u32(),
  ownerIdentity: __t.string(),
});
export type StoredFile = __Infer<typeof StoredFile>;

export const Transfer = __t.object("Transfer", {
  id: __t.u64(),
  pickupCode: __t.string(),
  ownerIdentity: __t.string(),
  createdAt: __t.timestamp(),
  expiresAtMicros: __t.u64(),
  sealed: __t.bool(),
});
export type Transfer = __Infer<typeof Transfer>;

export const TransferFileResult = __t.object("TransferFileResult", {
  id: __t.u64(),
  name: __t.string(),
  mimeType: __t.string(),
  sizeBytes: __t.u64(),
  createdAt: __t.timestamp(),
});
export type TransferFileResult = __Infer<typeof TransferFileResult>;

export const TransferResult = __t.object("TransferResult", {
  pickupCode: __t.string(),
  expiresAtMicros: __t.u64(),
  get files() {
    return __t.array(TransferFileResult);
  },
});
export type TransferResult = __Infer<typeof TransferResult>;

export const UploadLease = __t.object("UploadLease", {
  transferId: __t.u64(),
  expiresAtMicros: __t.u64(),
});
export type UploadLease = __Infer<typeof UploadLease>;

export const UploadSession = __t.object("UploadSession", {
  uploadToken: __t.string(),
  fileId: __t.u64(),
  nextChunkIndex: __t.u32(),
  receivedBytes: __t.u64(),
  createdAt: __t.timestamp(),
  chunkSizeBytes: __t.u32(),
  ownerIdentity: __t.string(),
});
export type UploadSession = __Infer<typeof UploadSession>;

export const UploadStatusResult = __t.object("UploadStatusResult", {
  transferId: __t.u64(),
  name: __t.string(),
  mimeType: __t.string(),
  sizeBytes: __t.u64(),
  chunkSizeBytes: __t.u32(),
  receivedBytes: __t.u64(),
  ready: __t.bool(),
  uploadedChunkIndexes: __t.array(__t.u32()),
});
export type UploadStatusResult = __Infer<typeof UploadStatusResult>;

